finvisor/expenses/routes.py
from flask import render_template, redirect, url_for, flash, request, abort, Blueprint
from flask_login import current_user, login_required
from finvisor import db
from finvisor.expenses.forms import ExpenseForm
from finvisor.models import Expense

expenses = Blueprint('expenses', __name__)


@expenses.route('/expense/new', methods=['GET', 'POST'])
@login_required
def new_expense():
    form = ExpenseForm()
    if form.validate_on_submit():
        if form.date.data:
            expense = Expense(date_of_expense=form.date.data, title=form.title.data, amount=form.amount.data, spender=current_user)
        else:
            # If no date entered, dont pass one in, so form uses default time of current time
            expense = Expense(title=form.title.data, amount=form.amount.data, spender=current_user)
        db.session.add(expense)
        db.session.commit()
        flash('Expense was added.', 'success')
        return redirect(url_for('main.home'))
    return render_template('input_expense.html', form=form, legend='Add New Expense')

@expenses.route('/expense/<int:expense_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_expense(expense_id):
    expense = Expense.query.get_or_404(expense_id)
    if expense.spender != current_user:
        abort(403)
    form = ExpenseForm()
    if form.validate_on_submit():
        expense.date_of_expense = form.date.data
        expense.title = form.title.data
        expense.amount = form.amount.data
        db.session.commit()
        flash('Expense Updated.', 'success')
        return redirect(url_for('main.home'))
    elif request.method == 'GET':
        form.date.data = expense.date_of_expense
        form.title.data = expense.title
        form.amount.data = expense.amount
    return render_template('input_expense.html', form=form, legend='Edit Expense')

@expenses.route('/expense/<int:expense_id>/delete', methods=['POST'])
@login_required
def delete_expense(expense_id):
    expense = Expense.query.get_or_404(expense_id)
    if expense.spender != current_user:
        abort(403)
    db.session.delete(expense)
    db.session.commit()
    flash('Expense Deleted.', 'success')
    return redirect(url_for('main.home'))

finvisor/incomes/routes.py
from flask import render_template, redirect, url_for, flash, request, abort, Blueprint
from flask_login import current_user, login_required
from finvisor import db
from finvisor.incomes.forms import IncomeForm
from finvisor.models import Income

incomes = Blueprint('incomes', __name__)


@incomes.route('/income/new', methods=['GET', 'POST'])
@login_required
def new_income():
    form = IncomeForm()
    if form.validate_on_submit():
        if form.date.data:
            income = Income(date_of_income=form.date.data, title=form.title.data, amount=form.amount.data, saver=current_user)
        else:
            income = Income(title=form.title.data, amount=form.amount.data, saver=current_user)
        db.session.add(income)
        db.session.commit()
        flash('Income was added.', 'success')
        return redirect(url_for('main.home'))
    return render_template('input_income.html', form=form, legend='Add New Income')

@incomes.route('/income/<int:income_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_income(income_id):
    income = Income.query.get_or_404(income_id)
    if income.saver != current_user:
        abort(403)
    form = IncomeForm()
    if form.validate_on_submit():
        income.date_of_income = form.date.data
        income.title = form.title.data
        income.amount = form.amount.data
        db.session.commit()
        flash('Income Updated.', 'success')
        return redirect(url_for('main.home'))
    elif request.method == 'GET':
        form.date.data = income.date_of_income
        form.title.data = income.title
        form.amount.data = income.amount
    return render_template('input_income.html', form=form, legend='Edit Income')

@incomes.route('/income/<int:income_id>/delete', methods=['POST'])
@login_required
def delete_income(income_id):
    income = Income.query.get_or_404(income_id)
    if income.saver != current_user:
        abort(403)
    db.session.delete(income)
    db.session.commit()
    flash('Income Deleted.', 'success')
    return redirect(url_for('main.home'))

finvisor/main/routes.py
from flask import render_template, request, Blueprint, url_for
from finvisor.models import User, Expense, Income
from flask_login import current_user


main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    #expenses = Expense.query.all()
    #income = Income.query.all()
    # Query for expenses and incomes by specific user, not all in DB
    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        expenses = Expense.query.filter_by(user_id=current_user.id).order_by(Expense.date_of_expense.desc()).paginate(page=page, per_page=10)
        income = Income.query.filter_by(user_id=current_user.id).order_by(Income.date_of_income.desc())
        # Get sum of all users expenses and incomes, number of, etc variables
        explist = list(Expense.query.filter_by(user_id=current_user.id))
        explen = len(explist)
        expsum = 0
        for e in explist:
            expsum += e.amount
        incsum = 0
        for i in list(income):
            incsum += i.amount
        
    else:
        # Will not show any data on home screen if user isnt logged in
        expenses = []
        income = []
        explen = 0
        expsum = 0
        incsum = 0
    return render_template('home.html', expenses=expenses, income=income, explen=explen, expsum=expsum, incsum=incsum)

@main.route('/about')
def about():
    author_pic = url_for('static', filename='profile_pics/' + 'author.jpg')
    return render_template('about.html', author_pic=author_pic)

finvisor/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from finvisor import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
from finvisor.users.forms import RegisterForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from finvisor.models import User
from finvisor.users.utils import send_reset_email


users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    # If already logged in, don't let user get back to register page
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegisterForm()
    if form.validate_on_submit():
        # Hash password
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        # Create a user
        user = User(username=form.username.data, email=form.email.data, password=hashed_pw)
        # Add user to database
        db.session.add(user)
        db.session.commit()
        # Give confirmation msg of creating an account
        flash('Successfully Created Account!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # Check if password matches hashed password stored in DB
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            # go to page user was trying to access if applicable using query param
            next = request.args.get('next') 
            # If correct email and password, log user in
            login_user(user, remember=form.remember.data)
            if next:
               return redirect(next)
            else: 
                return redirect(url_for('main.home'))
        else:
            flash('Login was unsuccessful. Check your email and password', 'danger')
    return render_template('login.html', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account Information Updated.', 'success')
        return redirect(url_for('users.account'))
    image_file = url_for('static', filename='profile_pics/' + 'default1.jpg')
    return render_template('account.html', image_file=image_file, form=form)

@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # Send user email to reset password
        send_reset_email(user)
        flash('Reset email sent.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None: # Took too long to click email, or not user
        flash('Invalid or Expired Token.', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_pw
        db.session.commit()
        flash('Successfully Updated Password!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', form=form)

finvisor/templates/about.html
{% extends "layout.html" %}
{% block head %}
    <title>FinVisor - About</title>
{% endblock head %}

{% block content %}
    <h1>About Page</h1>
    <p class='lead'>
        The FinVisor web app is a financial awareness tool created by Syed Rizvi.
        The idea originally started with a group of four programmers at the HackTX 2019
        hackathon, after which Syed continued working on the web app version of
        the program.
    </p>
    <p class='lead'>
        The aim of this app is to make people more aware of their financial standing
        by giving users a convenient place to input expenses and income. Future plans
        for the app include creating a system of financial advising on the app, to 
        give users further guidance and help them make more informed financial decisions.
    </p>
    <img class="rounded mx-auto d-block mb-5" src="{{ author_pic }}">
{% endblock content %}

{% block sidebox %}
    <h2>Information</h2>
    <p>Languages used:</p>
    <ul class='list-group'>
        <li class='list-group-item'>Python, Flask</li>
        <li class='list-group-item'>HTML, CSS</li>
    </ul>
{% endblock sidebox %}

finvisor/templates/account.html
{% extends "layout.html" %}
{% block head %}
    <title>FinVisor - Account</title>
{% endblock head %}

{% block content %}
    <h2>Account</h2>
    <div class="content-section">
        <div class="media">
          <img class="rounded-circle acc-img" src="{{ image_file }}">
          <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
          </div>
        </div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class='form-group'>
                <legend class='border-bottom mb-3'>Update Account Information</legend>
                <div class='form-group'>
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class='invalid-feedback'>
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class='form-group'>
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class='invalid-feedback'>
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class='form-group'>
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

{% block sidebox %}
    <h2>Account Status</h2>
    <p>General information</p>
    <ul class='list-group'>
        <li class='list-group-item'>Financal Status: (Good)</li>
        <li class='list-group-item'>Total Balance: #</li>
        <li class='list-group-item'>Visit Home tab for more info</li>
    </ul>
{% endblock sidebox %}

finvisor/templates/home.html
{% extends "layout.html" %}
{% block head %}
    <title>FinVisor - Home</title>
{% endblock head %}

{% block content %}
    <h1>Account Home</h1>
    <h2 class='text-danger mb-2'>Expenses for {{ current_user.username }}</h2>
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Date</th>
                <th scope="col">Title</th>
                <th scope="col">Amount</th>
            </tr>
        </thead>
        <!-- Example Expense.query.all() from database: [Expense('12/28/2019', '45'), Expense('Jan 1, 2020', '5')]  -->
        <tbody>
            {% for expense in expenses.items %}
                <tr>
                    {% if expense.spender == current_user %}
                        <th scope="row">{{ loop.index }}</th>
                        <td>{{ expense.date_of_expense.strftime('%Y-%m-%d') }}</td>
                        <td>{{ expense.title }}</td>
                        <td>
                            ${{ expense.amount }} 
                            <span class='ml-3'><a href="{{ url_for('expenses.edit_expense', expense_id=expense.id) }}">Edit</a></span>
                            <form action="{{ url_for('expenses.delete_expense', expense_id=expense.id) }}" method="POST" class="d-inline-block">
                                <input class="btn btn-danger btn-sm ml-3" type="submit" value="Delete">
                            </form>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <!-- If user is logged in, show paginate links, else error -->
    {% if expenses %}
        {% for expense_num in expenses.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if expense_num %}
                {% if expenses.page == expense_num %}    
                    <a class="btn btn-info mb-2" href="{{ url_for('main.home', page=expense_num) }}">{{ expense_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-2" href="{{ url_for('main.home', page=expense_num) }}">{{ expense_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
    {% endif %}

    
    <h2 class='text-success mb-2'>Income for {{ current_user.username }}</h2>
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Date</th>
                <th scope="col">Title</th>
                <th scope="col">Amount</th>
            </tr>
        </thead>
        <tbody>
            {% for i in income %}
                <tr>
                    {% if i.saver == current_user %}
                        <th scope="row">{{ loop.index }}</th>
                        <td>{{ i.date_of_income.strftime('%Y-%m-%d') }}</td>
                        <td>{{ i.title }}</td>
                        <td>
                            ${{ i.amount }}
                            <span class='ml-3'><a href="{{ url_for('incomes.edit_income', income_id=i.id) }}">Edit</a></span>
                            <form action="{{ url_for('incomes.delete_income', income_id=i.id) }}" method="POST" class="d-inline-block">
                                <input class="btn btn-danger btn-sm ml-3" type="submit" value="Delete">
                            </form>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

{% block sidebox %}
    <h2>Status</h2>
    <p>Display information on financial status here.</p>
    <ul class='list-group'>
        <li class='list-group-item'>Total Income: ${{ incsum }}</li>
        <li class='list-group-item'>Total Expenses: ${{ expsum }}</li>
        <li class='list-group-item'>Number of Expenses: {{ explen }}</li>
        <li class='list-group-item'>Overall Balance: ${{ incsum-expsum }}</li>
    </ul>
{% endblock sidebox %}

finvisor/templates/input_expense.html
{% extends "layout.html" %}
{% block head %}
    <title>FinVisor - Input Expense</title>
{% endblock head %}

{% block content %}
    <div class='content-section'>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class='form-group'>
                <legend class='border-bottom mb-4'>{{ legend }}</legend>
                <div class='form-group'>
                    {{ form.date.label(class="form-control-label") }}
                    {% if form.date.errors %}
                        {{ form.date(class="form-control form-control-lg is-invalid") }}
                        <div class='invalid-feedback'>
                            {% for error in form.date.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.date(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class='form-group'>
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class='invalid-feedback'>
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class='form-group'>
                    {{ form.amount.label(class="form-control-label") }}
                    {% if form.amount.errors %}
                        {{ form.amount(class="form-control form-control-lg is-invalid") }}
                        <div class='invalid-feedback'>
                            {% for error in form.amount.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.amount(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class='form-group'>
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

{% block sidebox %}
    <h2>Inputing Expenses</h2>
    <p>Tips:</p>
    <ul class='list-group'>
        <li class='list-group-item'>Enter date in the format: Year-Month-Day</li>
        <li class='list-group-item'>Enter monetary amount as a plain number.</li>
        <li class='list-group-item'>If left blank, the current time will be saved 
                                    for the inputed expense.</li>
        <li class='list-group-item text-danger'>Warning: If editing an expense, do not leave date field blank.</li>
    </ul>
{% endblock sidebox %}

finvisor/templates/input_income.html
{% extends "layout.html" %}
{% block head %}
    <title>FinVisor - Input Income</title>
{% endblock head %}

{% block content %}
    <div class='content-section'>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class='form-group'>
                <legend class='border-bottom mb-4'>{{ legend }}</legend>
                <div class='form-group'>
                    {{ form.date.label(class="form-control-label") }}
                    {% if form.date.errors %}
                        {{ form.date(class="form-control form-control-lg is-invalid") }}
                        <div class='invalid-feedback'>
                            {% for error in form.date.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.date(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class='form-group'>
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class='invalid-feedback'>
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class='form-group'>
                    {{ form.amount.label(class="form-control-label") }}
                    {% if form.amount.errors %}
                        {{ form.amount(class="form-control form-control-lg is-invalid") }}
                        <div class='invalid-feedback'>
                            {% for error in form.amount.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.amount(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class='form-group'>
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

{% block sidebox %}
    <h2>Inputing Income</h2>
    <p>Please Remember:</p>
    <ul class='list-group'>
        <li class='list-group-item'>Enter date in the format: Year-Month-Day</li>
        <li class='list-group-item'>Enter monetary amount as a plain number.</li>
        <li class='list-group-item'>If left blank, the current time will be saved 
            for the inputed expense.</li>
        <li class='list-group-item text-danger'>Warning: If editing income, do not leave date field blank.</li>
    </ul>
{% endblock sidebox %}

finvisor/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        
        <!-- Personal CSS in main.css file -->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

        <!-- Title block (shows up in tab), implemented in child html templates -->
        {% block head %}{% endblock %}
    </head>
    <body>
        <header class='site-header'>
            <nav class='navbar navbar-expand-md navbar-dark bg-success'>
                <div class='container'> <!-- container to get left margins -->
                    <div class='navbar-nav'>
                        <a class='nav-item nav-link' href="{{ url_for('main.home') }}">Home</a>
                        <a class='nav-item nav-link' href="{{ url_for('main.about') }}">About</a>
                    </div>
                    <!-- Navbar Right Side-->
                    <div class='navbar-nav'>
                        {% if current_user.is_authenticated %}
                        <a class='nav-item nav-link' href="{{ url_for('expenses.new_expense') }}">Add Expense</a>
                        <a class='nav-item nav-link' href="{{ url_for('incomes.new_income') }}">Add Income</a>
                        <a class='nav-item nav-link' href="{{ url_for('users.account') }}">Account</a>
                        <a class='nav-item nav-link' href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                            <a class='nav-item nav-link' href="{{ url_for('users.login') }}">Login</a>
                            <a class='nav-item nav-link' href="{{ url_for('users.register') }}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </nav>
        </header>
        <main class='container' role='main'>
            <div class='row mt-4'>
                <div class='col-md-8'>
                    <!-- Display messages here at top of page -->
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                                <div class='alert alert-{{ category }}'>
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                    {% block content %}{% endblock %}
                </div>
                <div class='col-md-4'>
                    <div class='content-section'> <!-- class for CSS styling -->
                        {% block sidebox %}{% endblock %} <!-- Let child templates implement what is inside sidebox
                        so that financial home page and login page show different info, etc. -->
                    </div>
                </div>
            </div>
        </main>
        

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1y
                YfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOY
                y5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih
                7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>

finvisor/templates/login.html
{% extends "layout.html" %}
{% block head %}
    <title>FinVisor - Login</title>
{% endblock head %}

{% block content %}
<div class='content-section'>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class='form-group'>
            <legend class='border-bottom mb-5'>Log In To Your Account</legend>
            <div class='form-group'>
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class='invalid-feedback'>
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class='form-group'>
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class='invalid-feedback'>
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class='form-check'>
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class='form-group'>
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
        <!-- Small Forgot Password link -->
        <small class='text-muted ml-2'>
            <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
        </small>
    </form>
</div>
<div class="pt-4">
    <small class='text-muted'>
        Don't Have An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up</a>
    </small>
</div>
{% endblock content %}

{% block sidebox %}
    <h3>Benefits of FinVisor</h3>
    <p>With this web app you can:</p>
    <ul class='list-group'>
        <li class='list-group-item'>Input your expenses and income</li>
        <li class='list-group-item'>Track your overall balance</li>
        <li class='list-group-item'>Convenient and user-friendly</li>
    </ul>
{% endblock sidebox %}